version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    tty: true

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ethiomed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  dbt:
  image: ghcr.io/dbt-labs/dbt-postgres:1.7.9  
  volumes:
    - .:/usr/app
  working_dir: /usr/app
  depends_on:
    - postgres
  entrypoint: ["/bin/bash"]
volumes:
  postgres_data:
